---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: mixed-line-ending
      - id: name-tests-test
        args: ['--django']
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shellcheck
      - id: shfmt
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
    hooks:
      - id: markdown-toc
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint-fix
  - repo: local
    hooks:
      - id: fix
        name: fix
        entry: poetry run task fix
        language: system
        pass_filenames: false
        always_run: true
      - id: lint
        name: lint
        entry: poetry run task lint
        language: system
        pass_filenames: false
        always_run: true
      - id: test
        name: test
        entry: poetry run task test
        language: system
        pass_filenames: false
        always_run: true
